name: gh-pages
on:
  workflow_run:
    workflows: ["cypress-test-e2e"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Cache dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Download build folder as artifact
        uses: actions/download-artifact@v3
        with:
          workflow: cypress-test-e2e.yml
          name: build


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: build
          clean: true
          force: true
